[package]
name = "solaris"
version = "0.1.0"
authors = ["Tomasz Drwięga <tomusdrw@gmail.com>"]

[dependencies]
ethabi = { git = "https://github.com/tomusdrw/ethabi.git" }
ethcore = { git = "https://github.com/paritytech/parity.git" }
ethcore-transaction = { git = "https://github.com/paritytech/parity.git" }
ethcore-bytes = { git = "https://github.com/paritytech/parity.git" }
ethereum-types = "0.3.2"
evm = { git = "https://github.com/paritytech/parity.git" }
lazy_static = "0.2"
vm = { git = "https://github.com/paritytech/parity.git" }
